//! GOLD-1 trajectory test (PLAN.md §14) — the normative serve-to-miss rally.
//!
//! Scenario: level 1, mouse pinned at the world center forever (paddle speed
//! ≡ 0), serve applied at tick 0. Reference values generated by the kit's
//! `golden_sim.py`; if this sim and those values disagree, this sim is wrong.
//!
//! One plan correction is baked in (see `DEVIATIONS.md` C1): the bonus drain
//! steps every **11** in-flight ticks (counter 10 → −1), so `bonusDisplay`
//! checkpoints land at f11 = 2975, f22 = 2950, f33 = 2925, … final 2675.

#![expect(
    clippy::expect_used,
    reason = "test assertions may unwrap scenario invariants"
)]

use curveball::consts::{WORLD_CX, WORLD_CY};
use curveball::sim::{CurveClass, SimEvent, SimInput, World, Zone};

/// Relative tolerance 1e-9 (the projection's `atan` may differ in the last
/// ulp across platforms). A zero expectation accepts either signed zero —
/// the signs that matter (Q10) are asserted bit-exactly at their ticks.
fn assert_rel(actual: f64, expected: f64, what: &str) {
    if expected == 0.0 {
        assert!(actual == 0.0, "{what}: {actual} != ±0.0");
        return;
    }
    let rel = ((actual - expected) / expected).abs();
    assert!(rel < 1e-9, "{what}: {actual} vs {expected} (rel {rel:e})");
}

/// (tick, x, y, z, vx, vy, cx, cy).
type TrajectoryRow = (u32, f64, f64, f64, f64, f64, f64, f64);

struct Harness {
    world: World,
    tick: u32,
    log: Vec<(u32, SimEvent)>,
}

impl Harness {
    /// Level-1 world in the Serve hold: enemy and ball on stage, every actor
    /// settled at the world center. Two warm-up ticks mirror Flash clip
    /// instantiation (no enterFrame on the placement frame) and let the ball
    /// cache the paddle snapshot the serve will read.
    fn new() -> Self {
        let mut world = World::new(curveball::sim::Published::default());
        world.level_setup();
        world.spawn_enemy();
        world.spawn_ball();
        let mut harness = Self {
            world,
            tick: 0,
            log: Vec::new(),
        };
        harness.run(0);
        harness.run(0);
        harness.tick = 0;
        harness.log.clear();
        harness
    }

    fn run(&mut self, clicks: u32) {
        self.tick += 1;
        let events = self.world.tick(&SimInput {
            mouse: (WORLD_CX, WORLD_CY),
            serve_clicks: clicks,
        });
        for event in events {
            self.log.push((self.tick, event));
        }
    }

    fn ball(&self) -> &curveball::sim::Ball {
        self.world
            .ball
            .as_ref()
            .expect("ball on stage for the whole scenario")
    }

    fn check_row(&self, row: &TrajectoryRow) {
        let (n, x, y, z, vx, vy, cx, cy) = *row;
        let ball = self.ball();
        assert_rel(ball.pos.x, x, &format!("f{n} x"));
        assert_rel(ball.pos.y, y, &format!("f{n} y"));
        assert_rel(ball.pos.z, z, &format!("f{n} z"));
        assert_rel(ball.vel.x, vx, &format!("f{n} vx"));
        assert_rel(ball.vel.y, vy, &format!("f{n} vy"));
        assert_rel(ball.curve.0, cx, &format!("f{n} cx"));
        assert_rel(ball.curve.1, cy, &format!("f{n} cy"));
    }
}

/// PLAN.md §14 table.
const TRAJECTORY: [TrajectoryRow; 9] = [
    (
        1,
        175.49,
        125.51,
        2.0,
        -0.01,
        -0.01,
        -0.009_960_159_362_55,
        -0.009_960_159_362_55,
    ),
    (
        2,
        175.470_039_841,
        125.529_960_159,
        4.0,
        -0.019_960_159_362_5,
        -0.019_960_159_362_5,
        -0.009_920_477_452_74,
        -0.009_920_477_452_74,
    ),
    (
        10,
        174.956_521_616,
        126.043_478_384,
        20.0,
        -0.098_226_086_464_2,
        -0.098_226_086_464_2,
        -0.009_608_661_010_1,
        -0.009_608_661_010_1,
    ),
    (
        37,
        168.794_689_725,
        132.205_310_275,
        74.0,
        -0.344_658_758_899,
        -0.344_658_758_899,
        -0.008_626_857_534_27,
        -0.008_626_857_534_27,
    ),
    (
        38,
        168.441_404_108,
        132.558_595_892,
        75.0,
        -0.353_285_616_433,
        -0.353_285_616_433,
        -0.008_592_612_514_64,
        -0.008_592_612_514_64,
    ),
    (
        76,
        148.951_372_744,
        152.048_627_256,
        0.0,
        -0.656_850_257_334,
        -0.656_850_257_334,
        0.0,
        0.0,
    ),
    (
        77,
        148.294_522_487,
        152.705_477_513,
        2.0,
        -0.656_850_257_334,
        -0.656_850_257_334,
        0.0,
        0.0,
    ),
    (
        114,
        123.991_062_966,
        177.008_937_034,
        75.0,
        -0.656_850_257_334,
        -0.656_850_257_334,
        -0.030_055_817_903_9,
        -0.030_055_817_903_9,
    ),
    (
        117,
        121.840_655_786,
        179.159_344_214,
        69.0,
        -0.746_658_955_232,
        -0.746_658_955_232,
        -0.029_698_014_326_6,
        -0.029_698_014_326_6,
    ),
];

/// (tick, bonusDisplay) — drains every 11 in-flight ticks.
const BONUS_CHECKPOINTS: [(u32, i32); 10] = [
    (10, 3000),
    (11, 2975),
    (22, 2950),
    (33, 2925),
    (37, 2925),
    (44, 2900),
    (76, 2850),
    (77, 2825),
    (114, 2750),
    (152, 2675),
];

/// (tick, enemy x, enemy y) — verifies the 1-tick publish lag and both
/// easing divisors (15 home, 17 chase at level 1).
const ENEMY_CHECKPOINTS: [(u32, f64, f64); 3] = [
    (2, 175.499_411_765, 125.500_588_235),
    (38, 172.231_734_731, 128.768_265_269),
    (114, 136.670_240_385, 164.329_759_615),
];

#[test]
fn gold1_trajectory() {
    let mut h = Harness::new();

    let mut trajectory = TRAJECTORY.iter().peekable();
    let mut bonuses = BONUS_CHECKPOINTS.iter().peekable();
    let mut enemies = ENEMY_CHECKPOINTS.iter().peekable();

    for tick in 1..=152 {
        h.run(u32::from(tick == 1));

        if tick == 1 {
            // Serve result: minimum-curve injection (−0.01, −0.01) from a
            // still paddle, observed after this tick's single decay step, and
            // the accuracy bonus for the centered ball.
            let ball = h.ball();
            let decayed_injection = -0.01_f64 / 1.004;
            assert_eq!(
                ball.curve.0.to_bits(),
                decayed_injection.to_bits(),
                "serve cx"
            );
            assert_eq!(
                ball.curve.1.to_bits(),
                decayed_injection.to_bits(),
                "serve cy"
            );
            assert_eq!(ball.vel.z.to_bits(), 2.0_f64.to_bits(), "serve vz");
            assert_eq!(h.world.economy.score, 100, "serve score");
            assert_eq!(h.world.economy.accuracy_bonus, 90, "serve accuracy degrade");
        }
        if tick == 76 {
            // Q10 signs: cx = −pSpeedX/25 = −0.0, cy = +pSpeedY/25 = +0.0;
            // the decay guard must then skip both.
            let ball = h.ball();
            assert_eq!(
                ball.curve.0.to_bits(),
                (-0.0_f64).to_bits(),
                "f76 cx is -0.0"
            );
            assert_eq!(ball.curve.1.to_bits(), 0.0_f64.to_bits(), "f76 cy is +0.0");
            assert_eq!(h.world.economy.score, 200, "f76 score");
            assert_eq!(h.world.economy.hit_score, 90, "f76 hitScore degrade");
            assert_eq!(h.world.economy.accuracy_bonus, 90, "f76 accuracy untouched");
        }

        if let Some(&&row) = trajectory.peek()
            && row.0 == tick
        {
            h.check_row(&row);
            trajectory.next();
        }
        if let Some(&&(n, expected)) = bonuses.peek()
            && n == tick
        {
            assert_eq!(h.world.economy.bonus_display, expected, "f{n} bonusDisplay");
            bonuses.next();
        }
        if let Some(&&(n, ex, ey)) = enemies.peek()
            && n == tick
        {
            assert_rel(
                h.world.enemy.as_ref().map_or(0.0, |e| e.pos.0),
                ex,
                "enemy x",
            );
            assert_rel(
                h.world.enemy.as_ref().map_or(0.0, |e| e.pos.1),
                ey,
                "enemy y",
            );
            enemies.next();
        }
    }
    assert!(trajectory.peek().is_none(), "all trajectory rows checked");
    assert!(bonuses.peek().is_none(), "all bonus checkpoints checked");
    assert!(enemies.peek().is_none(), "all enemy checkpoints checked");

    // Exact event log: order, ticks, payloads — and nothing else.
    let expected_events = [
        (
            1,
            SimEvent::Serve {
                zone: Zone::C,
                accuracy: true,
                curve: CurveClass::None,
            },
        ),
        (38, SimEvent::EnemyHit { zone: Zone::C }),
        (
            76,
            SimEvent::PlayerHit {
                zone: Zone::BL,
                accuracy: false,
                curve: CurveClass::None,
            },
        ),
        (114, SimEvent::EnemyHit { zone: Zone::BL }),
        (145, SimEvent::WallBounce { horizontal: false }),
        (152, SimEvent::PlayerMiss),
    ];
    assert_eq!(h.log, expected_events, "event log");

    // Post-miss state: lives, rally-bonus reset, bonusDisplay survival (Q8).
    assert_eq!(h.world.player_lives, 4);
    assert_eq!(h.world.economy.score, 200);
    assert_eq!(h.world.economy.hit_score, 100);
    assert_eq!(h.world.economy.curve_bonus, 50);
    assert_eq!(h.world.economy.super_curve_bonus, 150);
    assert_eq!(h.world.economy.accuracy_bonus, 100);
    assert_eq!(h.world.economy.bonus_display, 2675);
    let ball = h.ball();
    assert!(ball.stopped);
    assert_eq!(ball.vel.z.to_bits(), 0.0_f64.to_bits());
    assert_eq!(h.world.published.dir.z.to_bits(), 0.0_f64.to_bits());

    // One more tick: the ring pins to the published miss z clamped at 0
    // (player-side miss overshoots to z = −1 → ring shows full size).
    h.run(0);
    assert_eq!(h.world.ring_z.to_bits(), 0.0_f64.to_bits());
    assert_rel(h.world.published.pos.z, -1.0, "published miss z");
}
