world = new Object();
world.left = bounds._x;
world.right = bounds._x + bounds._width;
world.top = bounds._y;
world.bottom = bounds._y + bounds._height;
world.depth = 75;
world.speed = 2;
world.bounce = 1;
world.skillFactor = 17;
world.curveAmount = 50;
world.curveDecay = 0.01;
world.score = 0;
score = 0;
world.enemyLives = 3;
world.playerLives = 5;
world.level = 1;
level = "Level 1";
levelNumber = world.level;
world.bonus = 10;
world.bonusDisplay = 3000;
world.hitScore = 100;
world.curveBonus = 50;
world.superCurveBonus = 150;
world.accuracyBonus = 100;
world.hitDegrade = 10;
world.curveDegrade = 5;
world.superCurveDegrade = 15;
world.accuracyDegrade = 10;
bonusWord = "bonus:";
levelSkillFactor = new Array(17,14,11,9,7,5,3.5,2.75,2,1);
levelSpeed = new Array(2,2.33,2.66,3,3.33,3.66,4,4.33,4.66,6);
levelCurve = new Array(25,22.5,20,17.5,15,12.5,10,10,10,10);
wallBounce1 = new Sound();
wallBounce1.attachSound("wallBounce1");
wallBounce2 = new Sound();
wallBounce2.attachSound("wallBounce2");
pPaddleBounce = new Sound();
pPaddleBounce.attachSound("pPaddleBounce");
ePaddleBounce = new Sound();
ePaddleBounce.attachSound("ePaddleBounce");
missSound = new Sound();
missSound.attachSound("missSound");
globalSound = new Sound();
globalSound.attachSound(_root);
globalSound.setVolume(80);
